### ISSUE TITLE
No top menu

### ISSUE THREAD

**Issue by njadid** [OleVik/grav-skeleton-timeline#1]
I want to have the menu at the top in the timeline page. 
Can you provide some instructions on how it can be done?

**Comment by OleVik** [comment]
It largely depends on what your HTML and CSS looks like, is the timeline live on a website somewhere? If I can inspect the DOM I can find a solution rapidly.

**Comment by njadid** [comment]
Yes. It is here: http://hydrovise.com/navid.org/about

**Comment by OleVik** [comment]
Your theme will need to add the HTML-structure:

1. Create the file `/user/themes/MYTHEME/templates/partials/timeline_header.html.twig`, where `MYTHEME` is the folder for your theme.
2. This file is included by the plugin's Timeline-template, so any HTML added here will be included.
3. Add some HTML to create the menu, for example a simple icon:

```html
<div class="menu" style="
    position: fixed;
">
    <a href="#">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAAfklEQVR4nO3YsQ3DMAwEwHeQpbxHJskgXstrpQ/AxkDEwLwrCRYvFio+AQAAGGgr5u8k+8ogC5xJju/hs1jek7x+GudPPLoDdHOA7gDdqj/gXJpijTu+CQCAy/QBxbI+YAoH6A7QTR8AAMBQ+oBiWR8whQN0B+imDwAAAJjoA0RwDH+guMqLAAAAAElFTkSuQmCC">
    </a>
</div>
```
The CSS set on the uppermost element, `div.menu`, uses `position: fixed;` to move the icon with the page. Change it to `position: absolute;` to have it stay at the top. If you wanted a menu linking to other Pages in Grav, you could [follow this tutorial](https://learn.getgrav.org/16/cookbook/general-recipes#split-vertical-menu-system).

**Comment by njadid** [comment]
Thanks for the help!
